### ISSUE TITLE
forEach

### ISSUE THREAD

**Issue by Maksimus-Prime** [ValentinAlexandrovich/life#22]
По-максимуму везде где используешь forEach заменить на map. (ишьюс я посмотрю и закрою сам)
Почитай про разницу между методами map и forEach и сюда выпиши что понял :)
Один из источников https://codeburst.io/javascript-map-vs-foreach-f38111822c0f

**Comment by ValentinAlexandrovich** [comment]
Если кратко:

Метод «arr.forEach(callback[, thisArg])» используется для перебора массива.
Он для каждого элемента массива вызывает функцию callback.
Этой функции он передаёт три параметра callback(item, i, arr).
Метод forEach ничего не возвращает, его используют только для перебора, как более «элегантный» вариант, чем обычный цикл for.

Метод «arr.map(callback[, thisArg])» используется для трансформации массива.
Он создаёт новый массив, который будет состоять из результатов вызова callback(item, i, arr) для каждого элемента arr.

**Comment by ValentinAlexandrovich** [comment]
Более подробно будет при сдаче чек-листа)
Ишьюс исправлен, можешь закрывать.

**Comment by Maksimus-Prime** [comment]
Но ты все равно не назвал ключевое различие :) Читал статью которую я скинул?

**Comment by ValentinAlexandrovich** [comment]
.map() быстрее,  возвращает новый массив, оставляя исходный неизменным, .forEach() предпочтительнее если нет необходимости изменять исходный массив, а достаточно сохранить к примеру в базе данных или выполнить его регистрацию. Думаю, что то из этого)

**Comment by Maksimus-Prime** [comment]
А что лучше использовать если пишешь в функциональном стиле?

**Comment by ValentinAlexandrovich** [comment]
.map()

**Comment by Maksimus-Prime** [comment]
А почему?

**Comment by ValentinAlexandrovich** [comment]
потому, что forEach() влияет и меняет оригинальный массив, тогда как map()возвращает совершенно новый массив, оставляя исходный массив неизменным.

**Comment by Maksimus-Prime** [comment]
В точку) И это очень важно, а чем это так важно? тем что ты возвращаешь новое, а не мутируешь старое и в результате тебе не нужно походу выполнения всей программы держать множество состояний как может измениться переменная, если ее мутируют в разных местах, и FSD придерживается функционального подхода к программированию  (начинай уже активно читать про это, про концепции фп)
