### ISSUE TITLE
matrixEnd

### ISSUE THREAD

**Issue by Maksimus-Prime** [ValentinAlexandrovich/life#23]
https://github.com/ValentinAlexandrovich/life/blob/master/src/Model/model.ts#L10
Что это такое? Конец матрицы?)

**Comment by ValentinAlexandrovich** [comment]
Исправлено.

**Comment by Maksimus-Prime** [comment]
Не исправлено. что это такое? что прячется за этим названием? можешь объяснить?

**Comment by ValentinAlexandrovich** [comment]
Это была матрица нулевая матрица, размера игрового поля. Если значения матрицы игрового поля равны ей, значит игра завершена и выводился Алерт об этом состоянии.

**Comment by Maksimus-Prime** [comment]
А зачем для этого нужна целая матрица? почему нельзя просто проверить все на false? не пойму почему ты так сделал :) ладно, давай пока что делай правки по архитектуре, чуть позже доберемся и до этого, может быть походу рефакторинга ты ее сам выкинешь

**Comment by ValentinAlexandrovich** [comment]
Эта матрица и так исключена из проекта, решения по архитектуре уже реализовны. Осталось  ФП нормально реализовать.

**Comment by ValentinAlexandrovich** [comment]
И методы переименовать 🙂

**Comment by ValentinAlexandrovich** [comment]
Со всеми вытекающими для интерфейсов.

**Comment by Maksimus-Prime** [comment]
Принято, ждем-с пуш :)
