### ISSUE TITLE
Проверка объектов на равенство через JSON.stringify

### ISSUE THREAD

**Issue by Maksimus-Prime** [ValentinAlexandrovich/life#24]
Почитай почему это плохой способ сравнивать объекты и предложи другие варианты :)

**Comment by ValentinAlexandrovich** [comment]
Исправлено.

**Comment by Maksimus-Prime** [comment]
Так я тебя попросил предложить, мы с тобой обсудим, поговорим что хорошо а что плохо) Так почему плохо использовать JSON.stringify? и какие еще есть способы проверить объекты на равенство?

**Comment by ValentinAlexandrovich** [comment]
Сравнение посредством Json.stringify работает, когда имеются простые объекты стиля JSON без методов и узлов DOM, также важен порядок свойств в обьекте. Для простых объектов можно пробегаться циклом for in, для сравнения свойств, либо же если объекты являются масстивоподобными, то сначала преобразовать их посредством Array.from, а затем использовать уже имеющие методы. Так как здесь сравниваются на равенство масссивы, то предпочтительнее сначала использовать метод .every, для сравнения их элементов, а затем .some для проверки нахождения повторяющейся матрицы в массиве матриц состояний.
