### ISSUE TITLE
Условия окончания игры

### ISSUE THREAD

**Issue by Maksimus-Prime** [ValentinAlexandrovich/life#25]
Согласно каким правилам писал игру? которые в википедии?)

**Comment by ValentinAlexandrovich** [comment]
Исправлено. Добавлено условие сравнения текущего значения поля с предыдущими.

**Comment by Maksimus-Prime** [comment]
Валентин, это был не риторический вопрос, если спрашиваю, значит это важно. жду ответа

**Comment by ValentinAlexandrovich** [comment]
Правила взяты из Википедии конечно, но изначально не представлял как реализовать окончание по предыдущим состояниям игры, поэтому ограничился правилом нулевой матрицы.

**Comment by Maksimus-Prime** [comment]
Ну как, ты должен собирать все состояния в массив, который будет называться к примеру stateHistory и затем новое сравнивать с предыдущими и отдавать булево значение которое скажет тебе была такая конфигурация когда-то или нет :)

**Comment by Maksimus-Prime** [comment]
Еще у меня такое ощущение что ты не знаешь про типы данных в js и чем они отличаются :) Можешь рассказать что знаешь и в чем отличие? если нет, то обязательно прочти, это основа, фундамент, без которого будешь встречать ситуации которые будут казаться магией :)

**Comment by ValentinAlexandrovich** [comment]
Сейчас так и реализовано, со сбором состояний в массив, это было реализовано при первом исправлении ишьюса, метод называется stopGameCheck, масив matrixHistoryVariations.

**Comment by Maksimus-Prime** [comment]
И еще проблемы с английским :) в английском языке строго установленный порядок слов в предложении, стоит изучить его раз и затем будешь пользоваться постоянно и + к этому нужно изучить как именовать методы, т.е. они почти всегда начинаются с глагола, за исключением методов которые возвращают булево значение - is-*, has-*, это как раз в aibnb написано, а сам airbnb - требование у нас в стандартах
https://rizzoma.com/topic/a87a0a28b84d6326d4f3909e8801dab7/0_b_8nel_799u8/
https://github.com/airbnb/javascript#accessors--boolean-prefix

**Comment by ValentinAlexandrovich** [comment]
В js всего 7 типов данных, шесть примитивных (boolean[true, false], number[float], string[в UTF-16], null[литерал, который имеет значение null], undefined[свойство глобального обьекта undefined, которое имеет значение  undefined], symbol уникальный и неизменяемый тип данных), и object представляет собою коллекцию свойств(к нему же относятся функции и массивы). Примитивные типы не имеют методов и неизменяемы, но типы переменных, которым присвоено значение можно переназначать. Также примитивные типы(кроме nul и undefined) имееют объекты оболочки, что позволяет им назначать свойства, но не использовать их, так как он удаляется(процесс автоупаковки). Объекты хранятся в качестве ссылки. Создаются посредством new или литералов. Также у обьектов имеются функции конструкторы, позволяющие посредством прототипов добавлять к ним различные свойства. Все это отличает их от примитивных типов и методы

**Comment by ValentinAlexandrovich** [comment]
Объекты хранятся информацию в формате ключ, значение.

**Comment by ValentinAlexandrovich** [comment]
Про правила аэренби учту при реализации фп 🙂
