### ISSUE TITLE
Поменять цвета ui

### ISSUE THREAD

**Issue by Maksimus-Prime** [ValentinAlexandrovich/life#26]
Понимаю что мало относится к js, но поменяй плиз цвета, живые клетки от мертвых почти не отличаются цветом и приходится хорошо всматриваться :)
![2018-01-27 15-40-15](https://user-images.githubusercontent.com/27883524/35470253-87fbd9c4-0378-11e8-806d-58a098f3953c.png)
На зеленом фоне живые клетки будут смотреться гораздо четче (цвет: #146741)
![2018-01-27 15-43-30](https://user-images.githubusercontent.com/27883524/35470274-da528e3e-0378-11e8-90bb-7301baf667a4.png)

**Comment by ValentinAlexandrovich** [comment]
Исправлено.
