### ISSUE TITLE
es6-7

### ISSUE THREAD

**Issue by Maksimus-Prime** [ValentinAlexandrovich/life#27]
Почитай про нововведения, в частности про arrow-functions, spread operator и т.д.
Ниже распиши про что узнал и что нужно внедрить в твой проект, можно кратко)
babel как раз и нужен для чтобы использовать фишки завтрашнего javascript :)

**Comment by ValentinAlexandrovich** [comment]
Такое требование есть в стандартах?  Если можно, то просьба задавать ишьюсы ближе проекту. Есть чек лист по которому нужно будет сдаваться, но после того как закончится рефактор заданий. А пока расписывать инфу, которой полно нете, к заданием это не относится. Замечание закрываю. 🙂

**Comment by ValentinAlexandrovich** [comment]
Нашел две вот полезные вот такие статьи, пройдусь по проекту посмотрю что  и где можно будет применить) https://habrahabr.ru/post/313526/ https://habrahabr.ru/company/netologyru/blog/333604/

**Comment by Maksimus-Prime** [comment]
Хорошо, но лучше всегда искать источники на английском и изучать их)
