### ISSUE TITLE
Методы

### ISSUE THREAD

**Issue by Maksimus-Prime** [ValentinAlexandrovich/life#33]
Этот ишью не закрывай, здесь будут вопросы по тому что не понятно)
Распиши здесь плиз что за параметры принимает этот метод, что такое cellColumn и cellRow? Какую функцию выполняет этот метод?

**Comment by ValentinAlexandrovich** [comment]
Какой 'этот' метод?)

**Comment by Maksimus-Prime** [comment]
createChangeMatrix :)

**Comment by ValentinAlexandrovich** [comment]
Видоизменяет матрицу значений поля(0 или 1) по правилам игры, либо по нажатию на клетку мышью. cellRow и cellColumn значения столбца и строки поля, в котором нужно изменить значение на противоположное.

**Comment by ValentinAlexandrovich** [comment]
Примечание: *изменить в случае нажатия на клетку на поле.

**Comment by Maksimus-Prime** [comment]
Т.е. ты хочешь сказать что он ответственен и за перепросчет состояния поля в ходе игры, и за смену состояния клетки на которую кликнули?

**Comment by Maksimus-Prime** [comment]
Еще есть такие штуки как принципы проектирования (design principles) такие как DRY, DIE, KISS, SOLID и т.д., их тоже нужно придерживаться, почитай, это очень пригодится. И самое главное все что ты читаешь - это ничто без практики, а твое задание как раз та площадка где ты должен через это пройти, набить шишки и получить бесценный опыт
http://www.stijit.com/web-tips/dry-kiss-solid-yagni
https://habrahabr.ru/post/144611/

**Comment by ValentinAlexandrovich** [comment]
Да

**Comment by ValentinAlexandrovich** [comment]
Разобью на различные методы)
