### ISSUE TITLE
Метод map не используется для мутаций

### ISSUE THREAD

**Issue by Zarwlar** [ValentinAlexandrovich/life#34]
Мутации внутри методов, перебирающих массив, запрещены. Ты должен пробегаться по исходному массиву и записывать результат в какую-то константу

**Comment by ValentinAlexandrovich** [comment]
Почитай замечания, было заменить foreach на map

**Comment by ValentinAlexandrovich** [comment]
Закрытие замечания, называется forEach.

**Comment by Zarwlar** [comment]
Я в курсе) Ты просто заменил, но не переписал в соответствие с тем, что метод делает

**Comment by ValentinAlexandrovich** [comment]
Можно подробнее с примером, не понятно что тут требуется.

**Comment by ValentinAlexandrovich** [comment]
Хотя кажется понял, ок, перепишу.

**Comment by Zarwlar** [comment]
Так делать нельзя
```
const arrayChange: number[] = [];
array.map((arrayRow, i) => {
        arrayChange[i] = i;
}
```
Так делать можно и нужно)
```
const arrayChange: number[] = array.map((arrayRow, i) => {
        return arrayRow[i]i;
}
```

**Comment by ValentinAlexandrovich** [comment]
Исправлено.
