### ISSUE TITLE
Архитектура, ФП

### ISSUE THREAD

**Issue by Maksimus-Prime** [ValentinAlexandrovich/life#36]
Тебе нужно почитать про архитектуру приложений, про модульность, связность и зацепление модулей приложения, контракты которые предоставляют модули друг другу при взаимодействии.
Обязательно к прочтению по этой теме:
https://addyosmani.com/largescalejavascript/
https://habrahabr.ru/post/321050/
https://habrahabr.ru/post/276593/
А также тебе очень нужно почитать про функциональный javascript:
https://habrahabr.ru/post/154105/
https://github.com/MostlyAdequate/mostly-adequate-guide-ru
Еще я оставлял ссылку в одном из ишьюсов, там в книге круто описаны концепции ФП.
Все эти знания помогут тебе лучше понять что мы от тебя хотим, в противном случае тебе и нам придется очень долго сидеть над игрой и рассказывать что и как должно взаимодействовать, а тебе придется все это переделывать
По ходу чтения сравнивай со своим кодом и вноси правки в игру, в этом заключается требование ишьюса, если что-то походу не понятно, можешь спрашивать здесь, мы все будем тебе отвечать :)

**Comment by Maksimus-Prime** [comment]
Перенесу сюда из вопроса про createChangeMatrix
Еще есть такие штуки как принципы проектирования (design principles) такие как DRY, DIE, KISS, SOLID и т.д., их тоже нужно придерживаться, почитай, это очень пригодится. И самое главное все что ты читаешь - это ничто без практики, а твое задание как раз та площадка где ты должен через это пройти, набить шишки и получить бесценный опыт
http://www.stijit.com/web-tips/dry-kiss-solid-yagni
https://habrahabr.ru/post/144611/

**Comment by ValentinAlexandrovich** [comment]
Прежде всего, спасибо за статьи! Очень удачные и полезные подборки 🙂После прочтения статей по архитектуре, в голове сформировалась следующая структура: Вью, все что связано с домом плюсом сюда идёт регистрация контролёра как подписчика на события посредством паттерна наблюдатель, Модель это логика плюс данные, Контроллер реализация паттерна фасад.

**Comment by ValentinAlexandrovich** [comment]
Имеются еще какие-нибудь дополнения?

**Comment by Maksimus-Prime** [comment]
Да, все круто :) Только насчет фасада, распиши подробнее что ты под этим понимаешь

**Comment by ValentinAlexandrovich** [comment]
Я ориентируюсь на книжку Стоянка Стефонова, назвается javascript шаблоны и патерны примеры, которые добавил в репозиторий, думаю тоже очень полезная вещь. А в целом представляется как обьединение методов Вью и Модели, в методы контроллера, которые описывают процесс взаимодействия между ними.

**Comment by Maksimus-Prime** [comment]
"А реализует интерфейс модуля как правило специальный объект — Фасад." из статьи про мифический mvc
Думаешь ты правильно, в плане "обьединение методов Вью и Модели, в методы контроллера, которые описывают процесс взаимодействия между ними", но контроллер - это не фасад, фасад - это объект, который предоставляет высокоуровневое api для других модулей, и его можно выделить у любого модуля :)

**Comment by ValentinAlexandrovich** [comment]
Да, согласен.

**Comment by ValentinAlexandrovich** [comment]
Первые корректировки - пока что только на модели и контроллере.

**Comment by ValentinAlexandrovich** [comment]
Исправлено.
