### ISSUE TITLE
Все слои приложения вынести в отдельную папку

### ISSUE THREAD

**Issue by Maksimus-Prime** [ValentinAlexandrovich/life#37]
В src нужно создать папку mvc и в нее все это положить

**Comment by ValentinAlexandrovich** [comment]
Под слоями, я правильно понимаю, что это не только модель, вью, контроллер, а также интерфейсы , константы и индекс.тс ?

**Comment by Maksimus-Prime** [comment]
да, можно и так :)

**Comment by ValentinAlexandrovich** [comment]
Исправлено.
