### ISSUE TITLE
getters and setters

### ISSUE THREAD

**Issue by Maksimus-Prime** [ValentinAlexandrovich/life#38]
У тебя много методов начинающихся с get, set, нужно их перевести на геттеры и сеттеры
И почему ты здесь решил и присваивать и возвращать?
![2018-02-19 10-08-47](https://user-images.githubusercontent.com/27883524/36361211-f65848da-155c-11e8-97b9-ada96d366700.png)

**Comment by ValentinAlexandrovich** [comment]
Чтобы уменьшить зависимость модулей. В этом примере, для того чтобы контроллер обращался не к переменной модели, а использовал методы реализуемые моделью и представленные в интерфейсах.

**Comment by Maksimus-Prime** [comment]
Вопрос был в другом: почему ты в сеттере решил и присваивать и возвращать?

**Comment by Maksimus-Prime** [comment]
И поставь себе spell checker в vs code, очень пригодится :)
![2018-02-19 11-01-01](https://user-images.githubusercontent.com/27883524/36362126-5f73b5be-1564-11e8-906e-bf6f3209088a.png)

**Comment by ValentinAlexandrovich** [comment]
Передаю новое значение переменной из контроллера, а устанавливается в модели. Полученное значение присваиваю, и возвращаю в модель чтобы другие методы модели использовали обновлённое значение. Если вопрос состоит в чем то другом, опиши решение, через сайт трудно донести посыл)

**Comment by ValentinAlexandrovich** [comment]
Я в вебсторме работаю, не в вижуал 🙂

**Comment by ValentinAlexandrovich** [comment]
По поводу геттеров и сеттеров, внесу изменения.

**Comment by ValentinAlexandrovich** [comment]
А ещё было замечание, чтобы  методы имели возвращаемые значения.

**Comment by Zarwlar** [comment]
Под возвращаемыми значениями я подразумевал 
не **return**, а  
```
function add(x: number, y:number): **number** {
     return x + y;
}
```

**Comment by ValentinAlexandrovich** [comment]
Если не будет return значение будет void

**Comment by ValentinAlexandrovich** [comment]
Это тоже считать типом?

**Comment by Zarwlar** [comment]
Да

**Comment by ValentinAlexandrovich** [comment]
Принято, внесу изменения 🙂

**Comment by Maksimus-Prime** [comment]
Очень неявное поведение у твоей функции, почему она должна что-то возвращать? Ведь ты ее именуешь set
Передаю новое значение переменной из контроллера, а устанавливается в модели. Полученное значение присваиваю, и возвращаю в модель чтобы другие методы модели использовали обновлённое значение.

**Comment by ValentinAlexandrovich** [comment]
У меня это тот же вопрос вызвало когда писал, вопрос снят, счастья стало ясно что имелось ввиду. Изменения внесу.

**Comment by ValentinAlexandrovich** [comment]
Добавлены типы возвращаемых значений. От  get и set придется отказаться, поскольку для уменьшения зависимостей модулей в контроллере используются интерфейсы. А typescript не позволяет использовать get/set, только указать свойство в интерфейсе, что идет в конфронтацию с типом метода при вызове его в другом(в нашем случае контроллере). Вот здесь обсуждается этот вопрос об возможностях использования. https://stackoverflow.com/questions/12838248/is-it-possible-to-use-getters-setters-in-interface-definition Если не возникнет дополнений - ишью закрою.

**Comment by ValentinAlexandrovich** [comment]
Вопрос снят, в процессе редактирования.

**Comment by ValentinAlexandrovich** [comment]
Вьюху подправил, остальное пока в процессе)
