### ISSUE TITLE
Переделать Observer

### ISSUE THREAD

**Issue by Zarwlar** [ValentinAlexandrovich/life#39]
Сейчас в твоей реализации Observable не прослеживается чёткого распределения обязанностей между субъектом и наблюдателями. Отдели контракт, ответственный за уведомление об изменениях между объектами, от контракта роли объектов

**Comment by ValentinAlexandrovich** [comment]
У меня ведь и так отдельно метод уведомления об изменениях и отдельно регистрации, или что то другое имеются ввиду?

**Comment by Zarwlar** [comment]
Другое) Почитай про паттерн Наблюдатель

**Comment by ValentinAlexandrovich** [comment]
Исправлено.

**Comment by Zarwlar** [comment]
А что именно было исправлено?
