### ISSUE TITLE
Автоматический биндинг

### ISSUE THREAD

**Issue by Burize** [ValentinAlexandrovich/life#4]
Погугли про это. Можно или готовое что нибудь использовать или свое написать. Чтобы не было `private view = new View(this.getOptionsField.bind(this), this.getOptionsCell.bind(this), this.randomField.bind(this), this.startGame.bind(this), this.stopGame.bind(this));`

при данной реализации нужно каждый метод биндить при передачи куда-нибудь

**Comment by ValentinAlexandrovich** [comment]
Исправлено.
