### ISSUE TITLE
Распределение обязанностей по методам - хорошо, но

### ISSUE THREAD

**Issue by Zarwlar** [ValentinAlexandrovich/life#40]
Не стоит впадать в противоположную крайность и плодить кучу похожих методов. Есть множество методов, которые ты смог бы объединить в один без особого ущерба для читаемости кода

**Comment by Zarwlar** [comment]
isCondition вообще стоит убрать. Он используется один раз и заменяет &&. Стоит ли оно того, чтобы писать под это дело отдельный метод?

**Comment by Zarwlar** [comment]
И постольку, поскольку методов у тебя много (~39 в модели и ~44 во вьюхе), тебе стоит рассортировать и сгруппировать эти методы, согласно схожести задач, которыми они занимаются

**Comment by ValentinAlexandrovich** [comment]
Методы которые несут одинаковое назначения, я старался объединять в один, можно привести название методов, которые стоит объединить в единый, со стороны думаю это более очевидно выглядит)

**Comment by ValentinAlexandrovich** [comment]
Сортировка, это имеется ввиду порядок следования в программе?

**Comment by Zarwlar** [comment]
Да

**Comment by Zarwlar** [comment]
Например, всё что начинается на check, get, set можно объединить, и у тебя количество кода сократиться где-то на треть)

**Comment by ValentinAlexandrovich** [comment]
Хорошо, а про названия мтодов? При распределении старался придерживаться принципа чистых методов)

**Comment by Zarwlar** [comment]
Но не надо прям всё под один метод пихать, например getIndicatorOfStartGame носит явно уникальный характер, в отличие от getRow и getColumn

**Comment by Zarwlar** [comment]
Методы всё равно остануться чистыми. А что с именами? Ты можешь сделать им абстракные имена, вроде get() set(). А аргументы придумай)

**Comment by ValentinAlexandrovich** [comment]
Чистота потеряется ( когда переделывал методы, уже ощютил плюсы от распределения обязанностей. Удобнее работать с чистыми)

**Comment by ValentinAlexandrovich** [comment]
А понял, о чём идёт речь.

**Comment by ValentinAlexandrovich** [comment]
Исправлено.

**Comment by Zarwlar** [comment]
Вообще я немного другое подразумевал под универсальностью) Сейчас у тебя тебя вызов сеттера _создаёт_ новое поле в классе, а я имел в виду, что через один и тот же сеттер можно _обращаться_ к разным полям класса)
