### ISSUE TITLE
registerObserver

### ISSUE THREAD

**Issue by Maksimus-Prime** [ValentinAlexandrovich/life#41]
А почему ты решил провести регистрацию снаружи controller'a а не внутри?

**Comment by ValentinAlexandrovich** [comment]
Согласен, перенесу в контроллер, это будет логичнее.

**Comment by ValentinAlexandrovich** [comment]
Исправлено.

**Comment by Maksimus-Prime** [comment]
Ну и вынести все эти регистрации в отдельный метод, разве не явно? Плохо наступать на одни и те же грабли)
