### ISSUE TITLE
Spell Checker

### ISSUE THREAD

**Issue by Maksimus-Prime** [ValentinAlexandrovich/life#43]
Ты до сих пор юзаешь webstorm? На vs code еще не перешел?)
Для vs code есть расширение, которое подскажет если произошла опечатка
![2018-02-26 10-47-26](https://user-images.githubusercontent.com/27883524/36652665-ade4758e-1ae2-11e8-9f6c-68b5b5259ef5.png)
Lenght - Len**gth**

**Comment by ValentinAlexandrovich** [comment]
Чем плох вебсторм, у вас многие на нем сидят 🙂 надо поискать думаю что то подобное найдется)

**Comment by ValentinAlexandrovich** [comment]
Если не ошибаюсь он называется также, вечером поставлю 🙂

**Comment by ValentinAlexandrovich** [comment]
Исправлено.
