### ISSUE TITLE
Сеттер: первым аргументов идет ключ (имя элемента) потом уже все остальное

### ISSUE THREAD

**Issue by Burize** [ValentinAlexandrovich/life#44]
![2018-02-26 22 15 11](https://user-images.githubusercontent.com/22253666/36678145-930c5618-1b42-11e8-8f45-b6f549a0f237.png)

сильно сбивает столку. Тут не ясно кому что задается. Если не знать реализацию сеттера, которая обычно первым параметром принимает значения ключа, то вполне можно подумать, что каким то параметрам, которые есть в модели задается значение 'row'

**Comment by ValentinAlexandrovich** [comment]
У модели set get это не сеттеры и геттеры, а название методов, поэтому это будет переделано.

**Comment by ValentinAlexandrovich** [comment]
Исправлено.
