### ISSUE TITLE
методы с префиксами is/has должны возвращать булевое значение

### ISSUE THREAD

**Issue by Burize** [ValentinAlexandrovich/life#45]
![2018-02-26 22 24 03](https://user-images.githubusercontent.com/22253666/36678620-d010ed66-1b43-11e8-9cf2-bd44ab9836df.png)

По идее должен проверять наличие значения. По факту оборачивает обращение к полю в try-catch

**Comment by ValentinAlexandrovich** [comment]
Исправлено.
