### ISSUE TITLE
уменьшить зависимость (зацепленность) контроллера от view

### ISSUE THREAD

**Issue by Burize** [ValentinAlexandrovich/life#46]
![2018-02-26 22 35 27](https://user-images.githubusercontent.com/22253666/36679266-60485de6-1b45-11e8-9f0e-3d5cb2d77104.png)

сейчас контроллер знает о полях view. То есть его нельзя будет использовать с другим view, даже если оно точно такое же по архитектуре, но поля у нее будут названы по другому.

Для того, чтобы этого избежать обработчики событий должны принимать все необходимые данные (которые никак не относятся к конкретной реализации view).

------------

![2018-02-26 23 11 59](https://user-images.githubusercontent.com/22253666/36681217-983e4f26-1b4a-11e8-9758-44b676532dd6.png)

Например тут нужно просто принимать размеры поля от view и соответсвенно изменять размер массива в модели. 

\* Это один из вариантов, можно попробовать и другой подход

**Comment by ValentinAlexandrovich** [comment]
Его можно использовать с другой вьюхой потому как все реализуется через интерфейсы и  this.view.nameInputField - это сеттер. В интерфейсах оно показано как поле то потому так реализуются сеттеры через интерфейсы. Вот обсуждение этой темы https://stackoverflow.com/questions/12838248/is-it-possible-to-use-getters-setters-in-interface-definition  А то xто в модели именуется как set будет переработано -  это просто имя, а не сеттер.

**Comment by ValentinAlexandrovich** [comment]
а this.view.fieldParametrs - это геттер, поэтому если вьюха, имеет заявленные в интерфейсах методы- делать ее можно любой.

**Comment by Znack** [comment]
@Burize  Можно сеттеры оставить, там в #38 Макс предложил все на сеттеры переписать, пусть так будет. Хотя я сам сеттеры не люблю :)

**Comment by ValentinAlexandrovich** [comment]
Исправлено.
