### ISSUE TITLE
Про интерфейс View

### ISSUE THREAD

**Issue by Zarwlar** [ValentinAlexandrovich/life#48]
-> https://github.com/ValentinAlexandrovich/life/issues/39

**Comment by ValentinAlexandrovich** [comment]
Вот что было исправлено: 1) Контроллер, а не вьюха сам регистрируется посредством метода registerObserver, указывая событие на которое он подписывается и передает ссылку на свой метод, это заносится в объект observerList ввиде ключ значение. 2)Теперь при возникновения события(нажали кнопку , кликнули на клетку и т.д.) происходит поиск подписчика наименованию события в observerList, если такие имеются вызываются их соответсвующие методы.

**Comment by ValentinAlexandrovich** [comment]
А создание возможных событий, с добавлением соотвтсвующих свойтсв в объекте observerList происходит при инициализации вьюхи, посредством метода addEventListener.

**Comment by Zarwlar** [comment]
Теперь разобраться в IView стало ещё тяжелее)
Тебе нужно выделить отдельный интерфейс под Subject, а потом реализовать его. Помимо этого нужно избавиться от типов данных object и any. Создай свои типы / дополнительные интерфейсы

**Comment by ValentinAlexandrovich** [comment]
Отдельный класс Subject? View и Subject это не одно и тоже?

**Comment by ValentinAlexandrovich** [comment]
Я правильно понимаю, что нужно вынести методы регистрации, оповещения и отписки в отдельный класс Subject?

**Comment by ValentinAlexandrovich** [comment]
И реализовать типы посредством дженериков?

**Comment by Zarwlar** [comment]
Тебе нужно разделить логику между тем, что замешано в паттерне Observer, в частности, у субъекта, и логику MVC'шной View

**Comment by Zarwlar** [comment]
Типы можно реализовать через type или interface (это конструкции typescript). Возможно, где-то могут понадобиться Generic'и

**Comment by ValentinAlexandrovich** [comment]
Исправлено.
