### ISSUE TITLE
IView

### ISSUE THREAD

**Issue by Zarwlar** [ValentinAlexandrovich/life#49]
1. Здесь нужно создать отдельные типы под это дело.
2. Не являются ли эти типы слишком перегруженными? У тебя поле одновременно может быть и числом и булевым и двумерным массивом чисел. Возможно, плохо продумана логика работы этих методов

```
  createNewStateField(field: number | boolean | number[][]): JQuery<HTMLElement>[][];
  createInitField(field: number | boolean | number[][]): number[][];
```

**Comment by ValentinAlexandrovich** [comment]
Здесь и под это дело, это под эти два метода имеется ввиду?

**Comment by Zarwlar** [comment]
Под тип значения параметра методов

**Comment by ValentinAlexandrovich** [comment]
Дело не в реализации, а в наложенных ограничениях на игру. 1) Был ишьюс о том, что не стоит плодить схожие методы 2) был ишьюс, о том чтобы переделать методы на сеттеры и геттеры (этот вариант обсуждался и утвержден с Сергеем). В итоге получился универсальный метод parameter в модели, который по имени значения вычисляет и  изменяет параметры различный типов => number | boolean | number[][] А поскольку геттер и сеттер обязаны быть  с одинаковыми типами, то в методы для полей field createNewStateField и createInitField указываются эти значения number | boolean | number[][], так как в контроллере в эти методы передается геттер parameter. Создать для них свой интерфейсный тип тоже не пройдет такое решение , потому как эти типы не буду равны... В такие моменты понимаешь плюсы не строгой типизации в js)) Резюмируя, предлагаю ничего не менять :)) В крайнем случае, если вопрос принципиален, можно создать три одинаковых геттера, каждый будет работать со своим типом.

**Comment by ValentinAlexandrovich** [comment]
Через generics тоже не обойти, геттер и сеттер обязаны быть с одинаковыми типами. Вызывает ошибку. Вообщем жду фидбэка по этому вопросу)

**Comment by Zarwlar** [comment]
Это не обязательно менять, просто нужен был твой комментарий по этому поводу, почему так сделано)

**Comment by Zarwlar** [comment]
А ты типы то сделал или нет?)

**Comment by ValentinAlexandrovich** [comment]
Я же писал, это вызывает конфронтацию, при реализации сеттеров и геттеров, вчера пробовал это реализовать. Не удалось.

**Comment by ValentinAlexandrovich** [comment]
Мы ведь говорим о поле field только, верно?

**Comment by Zarwlar** [comment]
Да. Беда, ну ладно тогда
