### ISSUE TITLE
this.check

### ISSUE THREAD

**Issue by Maksimus-Prime** [ValentinAlexandrovich/life#52]
Что проверяет этот метод? По нему не понятно, у Макконнелла можешь прочитать про именование переменных и методов, тебе будет очень полезно :)

**Comment by ValentinAlexandrovich** [comment]
Метод проверяет граничные значения матрицы, для эмуляции поверхности тора, которое отображается в виде равномерной сетки. Имя метода переименовал, параметры метода тоже.
