### ISSUE TITLE
Именование

### ISSUE THREAD

**Issue by Maksimus-Prime** [ValentinAlexandrovich/life#53]
MAXIMUM_INPUT_VALUE: 25
Для какого инпута это минимальное значение? вообще не понятно, нужно конкретизировать
createDomElement - если посмотреть то это не просто какой-то абстрактный дом элемент, это конкретный элемент (который представляет собой templateDom), который нужно отразить в названии, а так у тебя получается что этот метод как будто принимает параметром какой элемент создать
А вообще видно что у тебя проблемы с именованием, изучи этот вопрос чтобы больше не наступать на одни и те же грабли (#52 ), вот список хороших источников, который поможет нам говорить друг с другом на одном языке :)
Прочти главы конкретно про именование
1. Читаемый код, или Программирование как искусство
2. Совершенный код

**Comment by ValentinAlexandrovich** [comment]
Во вьюхи два инпута эти константы используются для обоих, определяя допустимые границы вводимых значений размера поля. Первая книга очень порадовала, четкость изложения, картинки, примеры - удобна к почтению)) Буду более тщательно подходить к именованию переменных, методов и т.д.

**Comment by ValentinAlexandrovich** [comment]
Исправил на более конкретное название метода)
