### ISSUE TITLE
Разбить тесты на файлы в соответствие с теми слоями приложения, которые они тестируют

### ISSUE THREAD

**Issue by Zarwlar** [ValentinAlexandrovich/life#55]
Сейчас у тебя один файл, в котором тестируется всё подряд, и тебе нужно разбить его на несколько файлов. В качестве организации файлов, можешь, например, у каждого слоя mvc создать папку __tests__ и закидывать туда отдельный файлик с тестами

**Comment by ValentinAlexandrovich** [comment]
Там разбито все)

**Comment by ValentinAlexandrovich** [comment]
Отдельные файлы лежат в папке тест

**Comment by Zarwlar** [comment]
Ок)
