### ISSUE TITLE
проверка конца игры

### ISSUE THREAD

**Issue by Geksanit** [ValentinAlexandrovich/life#57]
```
private isStateIndicator = (): boolean => {
    if (this.isMatchOfArraysFound(this.matrixStateHistory)) {
      return this.indicatorOfEndGame = true;
    }
  }

  public isEndOfGame = (): boolean => {
    this.addArrayInArray(this.matrixStateHistory,this.matrix);
    this.updateArray(this.createChangeMatrix(this.matrix));
    this.isStateIndicator();
    return this.indicatorOfEndGame;
  }
```

**Comment by ValentinAlexandrovich** [comment]
?

**Comment by ValentinAlexandrovich** [comment]
В чем ишьюс?

**Comment by Zarwlar** [comment]
1. `isStateIndicator` — неудачное название;
2. Метод `isStateIndicator`, по сути дела, не нужен;
3. В методе `isStateIndicator` не все ветви кода возвращают значение (по идее, такое отслеживает чекер)
```
    if (this.isMatchOfArraysFound(this.matrixStateHistory)) {
      return this.indicatorOfEndGame = true;
    }

```
Этот код можно оставить в isEndOfGame, и там внутри этого же метода менять indicatorOfEndGame.
Вообще странно, что есть два индикатора indicatorOfEndGame и indicatorOfStartGame, причём, один из них **number**

**Comment by ValentinAlexandrovich** [comment]
Делов том что старт индикатор используется для отслеживания запуска игры, и блокировки бага с ускорением игры, при повторном нажатии кнопки старт. Значение он принимает number поскольку,  оно возвращается сет интрвал, и используется для клеар интервал.

**Comment by ValentinAlexandrovich** [comment]
Про метод статеиндикатор понятно, внесу изменения.

**Comment by Zarwlar** [comment]
Как-то это странно, что от indicatorOfStartGame зависит столько вещей

**Comment by ValentinAlexandrovich** [comment]
По сути эта переменная, значение которой используется в различных методах модели

**Comment by Zarwlar** [comment]
Ну это очень нейтральное представление о том, что делает эта переменная)
По сути дела,

1. Она решает проблемы, которых вообще быть не должно (баг с ускорением (???));
2. Влияет на состояние поля вместе с indicatorOfEndGame;
3. Хранит id таймера

По хорошему, должна быть булева переменная, ответственная за состояние поля (либо есть динамика на поле, либо поле пустое), и должен быть таймер id. Причём с явным названием, что это именно id таймера и для чего он используется

**Comment by ValentinAlexandrovich** [comment]
Хорошо, согласен, внесу изменения.

**Comment by ValentinAlexandrovich** [comment]
Исправлено.
