### ISSUE TITLE
Обсуждение кода

### ISSUE THREAD

**Issue by Geksanit** [ValentinAlexandrovich/life#58]
Может в процессе обсуждения мы поймем что вообще происходит и ты поймешь где ошибка. Что делает метод initName в модели ?

**Comment by ValentinAlexandrovich** [comment]
Это связка геттера параметр и инит нэйм, для установки имени параметра который необходимо получить.

**Comment by ValentinAlexandrovich** [comment]
Поскольку геттер ничего не возвращает, приходиться так извращаться.

**Comment by ValentinAlexandrovich** [comment]
А метод гет, универсальный для различных параметров используется.

**Comment by Geksanit** [comment]
т.е. таким  трюком можно обращаться к полям модели из контроллера ?

**Comment by Geksanit** [comment]
я правильно понял что вот это -
```
public startGame = (): void => {
    this.model.initName = {nameParameter: 'indicatorOfStartGame'};
    if (!this.model.parameter['value']) {
```
тоже самое что и вот это - 
```
public startGame = (): void => {
    if (!this.model.indicatorOfStartGame) {
```

**Comment by ValentinAlexandrovich** [comment]
Да.

**Comment by Geksanit** [comment]
Так зачем такие сложности ? обращайся к полям модели напрямую. Делай проще ! )))

**Comment by ValentinAlexandrovich** [comment]
Но обращение не на прямую идет, а через метод.

**Comment by ValentinAlexandrovich** [comment]
Это ослабляет ее зависимость контроллера от модели.

**Comment by ValentinAlexandrovich** [comment]
Методы описываются в интерфейсах, а контроллер их использует.

**Comment by Geksanit** [comment]
Зависимость не ослабляется, там же в контроллере прописано "indicatorOfStartGame" а значит о любая модель должна иметь "indicatorOfStartGame". В этом случае разницы нет прямо или косвенно обращаться к indicatorOfStartGame !

**Comment by Geksanit** [comment]
или можно заменить три метода одним, который возвращает поле модели

**Comment by Geksanit** [comment]
например 
public get parameter(nameParameter):IParameter {
    return this[nameParameter];
  }

**Comment by ValentinAlexandrovich** [comment]
Не согласен, вот статья
https://m.habrahabr.ru/post/321050/

**Comment by ValentinAlexandrovich** [comment]
У меня так было изначально, сказали передать на сеттер и геттеры, переделывать обратно я не буду.

**Comment by ValentinAlexandrovich** [comment]
Статья по уменьшение зависимостей

**Comment by ValentinAlexandrovich** [comment]
По поиску можно найти"особенно хорошо раскрыта тема моделей" чуть ниже середины статьи.

**Comment by ValentinAlexandrovich** [comment]
''Особенно хорошо тема Моделей"

**Comment by ValentinAlexandrovich** [comment]
Твой код не будет работать, потому как геттер ничего не принимает в качестве параметра.

**Comment by Geksanit** [comment]
принимет аргумент nameParameter - строка, считай что это был псевдокод.

**Comment by Geksanit** [comment]
метод принимает строку и возвращает соответствующее поле модели.

**Comment by ValentinAlexandrovich** [comment]
Напиши геттер в тайп скрипте и ты поймёшь, о чем я говорю🙂 Он выдаст ошибку, и напишет что в геттеры не передаются параметры.

**Comment by Geksanit** [comment]
ты прав

**Comment by ValentinAlexandrovich** [comment]
Закрываю ишью?

**Comment by Geksanit** [comment]
нет, я сам закрою

**Comment by ValentinAlexandrovich** [comment]
Думаю стоит добавить здесь ещё пару строчек на обсуждаемую тему.🙂 Сейчас методы контроллера позволяют обращаться к методам модели по его имени через методы обьявленные в интерфейсах, но представим противоположное (с зависимостью от имен модели) и потребовалось добавить в проект ещё одну модель схожую по архитектуре, но имеющую другие имена полей. В этом случае использование контроллера, как есть без видоизменений его методов, не представляется возможным, что влечет увеличение кода и т.д. Думаю более остро можно ощутитьна эту ситуацию если перенести это видение на Вьюху, которая в проекте может быть реально не одна.

**Comment by Geksanit** [comment]
Верно. В контроллере достаточно вынести строки(имена методов) в константы.

**Comment by Geksanit** [comment]
Тогда уже и строки - сообщения тоже в константы выноси. Если константа много получится, тогда в отдельный файл для констант.

**Comment by ValentinAlexandrovich** [comment]
Строки (Имена методов) в сабжект которые? Или еще имена полей типа матрикс,  индикатор, роутер, колумн ит.д.?

**Comment by ValentinAlexandrovich** [comment]
Думаю имеет смысл перенести все строковые значения из контроллера в константы?

**Comment by Geksanit** [comment]
Да, все строки в константы.

**Comment by Zarwlar** [comment]
Валентин, а ты придёшь в субботу к нам?:)

**Comment by ValentinAlexandrovich** [comment]
Да🙂

**Comment by Zarwlar** [comment]
Давай лучше в воскресенье?) Просто в субботу могут возникнуть проблемы с возможностью появиться на работе :)

**Comment by ValentinAlexandrovich** [comment]
В воскресенье не уверен что получится, в субботу точно приду.

**Comment by Zarwlar** [comment]
Окей, давай в субботу) А ты во сколько будешь?

**Comment by ValentinAlexandrovich** [comment]
Подьеду часам к 10, обратно думаю в часик 6-7 поеду)

**Comment by ValentinAlexandrovich** [comment]
Исправлено.
