### ISSUE TITLE
Упростить код

### ISSUE THREAD

**Issue by Geksanit** [ValentinAlexandrovich/life#59]
```
  public changeTypeCell = (event): void => {
    this.model.parameter = {nameParameter: 'cellRow', value: this.view.identifyCellParameters('row', event)};
    this.model.parameter = {nameParameter: 'cellColumn', value: this.view.identifyCellParameters('column', event)};
    this.model.changeMatrixByClickingOnCell();
```
Тут передаются аргументы для функции через параметры, можно передать их как аргументы функции.

**Comment by Geksanit** [comment]
Тогда и cellRow, cellColumn в модели не нужны.

**Comment by ValentinAlexandrovich** [comment]
1) как универсальный метод поймет что это за значение (какому полю его присвоить)? 2) в тайпскрипте если связанные гет и сет имеют разные типы возвращаемых и передаваемых значений соответственно, это вызывает ошибку.

**Comment by ValentinAlexandrovich** [comment]
А еще гет и сет это в интерфейсах идут как поля а не методы, и передать параметры в скобочках (какой то параметр для сет) нельзя, это тоже вызывает ошибка 🙂

**Comment by ValentinAlexandrovich** [comment]
А описать сет и нет в интерфейсах, как методы тоже нельзя, вызовет опять же ошибку.

**Comment by Geksanit** [comment]
Я не про это. В модели есть cellRow, ты записываешь туда число, а потом вызываешь функцию changeMatrixByClickingOnCell() которая использует cellRow. Можно вызвать метод changeMatrixByClickingOnCell() и передать ему аргументы "changeMatrixByClickingOnCell(a, b)".

**Comment by ValentinAlexandrovich** [comment]
Исправлено.
