### ISSUE TITLE
Интерфейсы

### ISSUE THREAD

**Issue by Geksanit** [ValentinAlexandrovich/life#60]
Интерфейс - это декларация доступных методов/свойств. Если контроллер использует row в модели, значит row должно быть прописано в интерфейсе и быть публичным в модели. Если контроллер не использует row, то всё должно быть наоборот.

**Comment by Geksanit** [comment]
Исправь все интерфейсы и публичность.

**Comment by ValentinAlexandrovich** [comment]
Поясню, про свойства в модели. Они все могут и изначально такими являются - приватными, я сделал некоторые из них публичными лишь для того чтобы, в тестах к контроллеру при вызове методов изменяющих свойства модели, проверять что свойства действительно изменились.

**Comment by ValentinAlexandrovich** [comment]
А так можно передать их в приватные, от этого работоспособность кода не изменится, только в тестах придется отказаться от проверки приватных свойств.

**Comment by ValentinAlexandrovich** [comment]
Могу предложить как вариант все свойства в модели в приватные перевести, а тесты контролёра дополнить получающими свойства их модели вызовами методов, и уже возвращенные значения сравнивать на правильность.

**Comment by Geksanit** [comment]
Проще всего не создавать себе проблем и убрать вообще приватность/публичность. Либо в тестах проверять свойства через initName paremeter.

**Comment by ValentinAlexandrovich** [comment]
Исправлено.
