### ISSUE TITLE
Обсуждение кода

### ISSUE THREAD

**Issue by Geksanit** [ValentinAlexandrovich/life#64]
Том первый глава вторая )))

**Comment by Geksanit** [comment]
Почему в модели для описания состояния ячейки используется число?

**Comment by ValentinAlexandrovich** [comment]
Удобно работать с методами массивов🙂

**Comment by ValentinAlexandrovich** [comment]
А ещё количество соседей живых тоже удобно посчитать.

**Comment by ValentinAlexandrovich** [comment]
Закрываю ишьюсы?
