### ISSUE TITLE
Излишняя универсальность методов

### ISSUE THREAD

**Issue by Geksanit** [ValentinAlexandrovich/life#65]
Под универсальностью я имею в виду возможность метода получить в аргументе любой объект.
Конкретнее: 
В модели есть матрица, она всегда одна. Все методы которые получают эту матрицу в качестве аргумента, обрабатывают только её. Если эти методы сделать такими, чтобы они эту матрицу брали не как аргумент а напрямую `this.matrix`. То от этого ничего не сломается, и кода станет меньше.
Сами методы:
`createChangeMatrix`
`countQuantityOfLivingCellsAround`
`createRandomArray` `createRandomMatrix` - из этих двух нужно сделать один.

**Comment by ValentinAlexandrovich** [comment]
Исправлено.

**Comment by Maksimus-Prime** [comment]
Добавь плиз opacity: 0.4; в классе .field__cell_uncheck**ed**
а вообще зачем тебе два типа модификаторов? почему бы по дефолту не сделать цвет такой как в uncheck**ed**, а если нажали на  клетку добавить модификатор checked
