### ISSUE TITLE
Конструктор класса должен быть максимально легковесным

### ISSUE THREAD

**Issue by Maksimus-Prime** [ValentinAlexandrovich/life#66]
Из стандартов: Конструктор класса должен быть максимально легковесным.
Вынести в отдельный метод registerObservers
    this.view.registerObserver('create', this.createDomItemsByPageTemplate);
    this.view.registerObserver('start', this.startGame);
    this.view.registerObserver('clear', this.clearField);
    this.view.registerObserver('changeSize', this.changeSizeField);
    this.view.registerObserver('pause', this.pauseGame);
    this.view.registerObserver('random', this.createRandomField);
    this.view.registerObserver('clickCell', this.changeTypeCell);
    this.model.registerObserver('newStateMatrix', this.getNewStateMatrix);
![2018-03-19 11-29-11](https://user-images.githubusercontent.com/27883524/37578053-c8830d24-2b68-11e8-9d52-63c180617707.png)

**Comment by ValentinAlexandrovich** [comment]
Исправлено.
