### ISSUE TITLE
Передавать аргументы через аргументы)

### ISSUE THREAD

**Issue by Geksanit** [ValentinAlexandrovich/life#70]
```
  private initParamsField = (message: string): void => {
    this.model.rows = this.view.getFieldParameters('rows');
    this.model.columns = this.view.getFieldParameters('columns');
    this.model.createNewMatrix();
    this.view.changeScoreboardMessage(message);
  }
```
Здесь можно передавать число строк и колонок как аргументы метода createNewMatrix(), а в нем уже назначать поля `this.rows this.columns`. А т.к. эти параметры больше в контроллере не используются, то их нужно убрать из интерфейса модели и сделать приватными.

**Comment by ValentinAlexandrovich** [comment]
Исправлено.
