### ISSUE TITLE
Observer

### ISSUE THREAD

**Issue by Geksanit** [ValentinAlexandrovich/life#71]
Какой должен быть observer:
Каждый ивент (отправитель событий) должен быть полем модели/вью. Сам по себе являться инстаносом универсального класса событий. Каждый этот ивент  должен получать свой интерфейс через generic. Это позволит определить интерфейс сообщений, которые получает слушатель.

Сейчас каждый ивент - это элемент ассоциативного массива ObserverList. И они не имеют своих методов. Из-за этого не возможно реализовать весь потенциал типов TS.

Что нужно сделать:
Написать класс ивентов, с теми же методами что сейчас обрабатывают observerList, но немного изменёнными.
Почитать про generics ts (обобщённые типы). 
Написать классу ивентов интерфейс.

**Comment by Geksanit** [comment]
Когда это будет сделано, слушатели смогут получать только нужные данные, а не что попало.

**Comment by ValentinAlexandrovich** [comment]
Исправлено.
