### ISSUE TITLE
Переименовать

### ISSUE THREAD

**Issue by Geksanit** [ValentinAlexandrovich/life#78]
Замечания по модели:
В модели не должно быть element и elements. Речь же не об абстрактных элементах, а о клетках игры (т.е. cell и cells).

Никто из ребят не смог понять смысл переменных по названиям:
`currentValuePositionRangeOfRow`, `currentValuePositionRangeOfColumn`, `isMatchOfArraysNotFound`.

У матрицы в рамках Игры есть поколения, а не состояния

У матрицы генерируются не `новые` состояния, а `следующие`

`if (!this.matrix[indexOfRow][indexOfColumn] || (currentValuePositionRangeOfRow === 0 && currentValuePositionRangeOfColumn === 0)) { return countOfColumn; }` 
Не пиши в одну строчку (выше в твоём коде есть аналогичный код)
Вынеси содержимое условия в отдельный приватный метод.

if (!this.matrix[indexOfRow]) { return countOfRow; } 
Почему такая проверка границы? Можно же использовать indexOfRow и this.row. Аналогичном с другим сравнением в том же редюсе.

arrayRow -> row

**Comment by Geksanit** [comment]
Контроллер:

Никто из ребят не смог понять смысл переменной по названию `indicatorOfFieldDynamics` 

getCellDataParameter -> getCellData

changeClassCell -> changeCellClass

Зачем каждый раз idTimerForStartGame кастовать в Number?

changeTypeCell -> хотя бы changeCellType

checkGameStop -> название не говорит о том, что в нём может произойти остановка игры

**Comment by Geksanit** [comment]
IInstance - это что, пустой интерфейс ?

**Comment by ValentinAlexandrovich** [comment]
indicatorOfFieldDynamics - был ишью По хорошему, должна быть булева переменная, ответственная за состояние поля (либо есть динамика на поле, либо поле пустое), и должен быть таймер id. Причём с явным названием, что это именно id таймера и для чего он используется #57

**Comment by ValentinAlexandrovich** [comment]
'В модели не должно быть element и elements. Речь же не об абстрактных элементах, а о клетках игры (т. е. cell и cells) => ' по уровню абстракции клетки находятся во вьюхе, а в моделе как раз элементы массива.

**Comment by ValentinAlexandrovich** [comment]
Массив содержит элементы, а клетка является Дом элементом отображаемым Вьюхой.

**Comment by Zarwlar** [comment]
Не, я имею ввиду, из-за чего (на каком этапе) происходит абстрагирование уровня абстракции модели предметной области модели от уровня абстракции модели предметной области вьюхи? Ведь это же одна и та же сущность. Или нет?

**Comment by ValentinAlexandrovich** [comment]
Границей абстрагирования является класс, а его инстанс это сущность. Если продолжить твою мысль, то допустим мне захочется добавить цветовую зависимость кнопок, информационного поля от количества живых клеток в игре, тогда необходимо будет назвать уже не cell, а cellButton, да и в целом при таком подходе весь проект можно увязать через навязывание зависимостей в одну сущность.

**Comment by Zarwlar** [comment]
Принято)

**Comment by ValentinAlexandrovich** [comment]
Исправлено.
