### ISSUE TITLE
обсуждение вью

### ISSUE THREAD

**Issue by Geksanit** [ValentinAlexandrovich/life#79]
IInstance - это что, пустой интерфейс ?
Опиши работу вьюхи, как она у тебя устроена, какие методы как используются.

**Comment by Geksanit** [comment]
Большинство имен методов, аргументов, переменных не позволяют понять код.

**Comment by ValentinAlexandrovich** [comment]
createGameWithInitialParameters - создать игру с исходными параметрами,
notifySubscribersByEvents - подписать на события,
valueInput - значение инпута,
getBoundaryOfFieldByInput - получить границу поля для инпут,
renderField  - отрисовать поле,
rerenderField - перерисовать поле,
createItemByTemplate - создать элемент по шаблону,
createDomItemsByPageTemplate - создать дом элементы по шаблону,
changeScoreboardMessage - изменить сообщение табло
changeClassCell - изменить класс клетки
isDeadCell - проверить мертва ли клетка
getCellDataParameter - получить от клетки дата параметер

**Comment by ValentinAlexandrovich** [comment]
IInstance - интерфейс интстанса, был ишью избавиться от <object>

**Comment by ValentinAlexandrovich** [comment]
object  и any

**Comment by Zarwlar** [comment]
Да, был такой ишью, и ты его исправил. Вот те изменения)
https://github.com/ValentinAlexandrovich/life/commit/3632272ddc800f3ed21ef2dd28383643f9bc4b8a#diff-97d90e251d74e6690a312ff2de2d3b98L26

 А откуда IInstance то взялся?)

**Comment by ValentinAlexandrovich** [comment]
Исправлено.
