### ISSUE TITLE
Model

### ISSUE THREAD

**Issue by Burize** [ValentinAlexandrovich/life#8]
При нынешней реализации модели по сути нет. Есть просто набор функций, которые делают матрицы (двумерные массивы). В модели должно храниться текущее состояние поля, все операции, которые изменяют поле также должны происходить внутри нее. Соответсвенно проверка на то, законченная ли игра и подобные штуки напрямую взаимодейстующие с состоянием поля все они должны быть реализованы внутри нее. 

view обрабатывает событие вызванные пользователем. Контроллер передает view текущее состояние поле и при необходимости (например изменение размера поля) вызывает у модели соответствующие методы. А модель уже напрямую взаимодействует с полем (она хранит его состояние).

**Comment by ValentinAlexandrovich** [comment]
Исправлено.
