### ISSUE TITLE
Тайпинги

### ISSUE THREAD

**Issue by Zarwlar** [ValentinAlexandrovich/life#80]
Возможно, у тебя стоят какие-то глобальные тайпинги для ts, но при клонировании твоего репозитория в файлах IVIew view появляются ошибки тайпингов, связанных с JQuery, $, require

![image](https://user-images.githubusercontent.com/26929933/38009256-7120f11a-327d-11e8-954b-5d7fec4d3f64.png)
![image](https://user-images.githubusercontent.com/26929933/38009250-68be7da8-327d-11e8-93ed-2d25406c264b.png)

**Comment by ValentinAlexandrovich** [comment]
Исправлено.
