### ISSUE TITLE
Вопросы по рефакторингу

### ISSUE THREAD

**Issue by Geksanit** [ValentinAlexandrovich/life#82]
1. fixPastBoardStates - почему fix ?
2. getNextCellState - почему бы сразу не возвращать 1 или 0 ?
3. isNotRepeatBoard - переименовать в isBoardRepeated, без Not и переделать соответствующе.
4. clearPastBoardStates - не возвращать ничего после присваивания.
fixPastBoardStates, toggleCellState - тоже самое. 
5. в getAliveNeighborsCount из редюсов вынести коллбэки в отдельные функции.
6. countRowIndex - не понятно где RowIndex, расскажи индекс какой строки считается и где находится эта строка.
во вью
7. GameTemplate - почему с большой буквы ?
8. в renderField зачем два класса? .js-field__row.field__row
9.  в getFieldTemplate нужно выделить в отдельную функцию конвертации из формата поля в формат нужный jsrender'у
10. в changeCellClass _check -> **_checked**
11. changeCellClass не переделал работу с DOM узлами
в контроллере
12. idTimerForStartGame -> gameTimer
13. c checkGameStop - мы решили оставить так или мы переделали это?
14. changeCellType - тоже переименовывали, вспоминай)

**Comment by ValentinAlexandrovich** [comment]
Исправлено.
